### ISSUE TITLE
Map doesn't work

### ISSUE THREAD

**Issue by TheLastGimbus** [waarzitjenu/server#59]
Hi there!
I've spined up the whole server (back + front end) with docker-compose, and filled `.env.local` with correct values:
```
VUE_APP_LOCATION_API_ENDPOINT="https://waar.matih.duckdns.org/retrieve"
VUE_APP_MAPBOX_ACCESS_TOKEN="fsdhsdajkghsajgsahlfg..."
```
But map doesn't work:
![image](https://user-images.githubusercontent.com/40139196/120123312-62bdac80-c1ae-11eb-8c6e-c5f3c6c1d2b6.png)

I have it public, so you can even check this yourself: https://waar.matih.duckdns.org/

**Comment by ricardobalk** [comment]
I just merged https://github.com/waarzitjenu/map/commit/5bf01903e3e10a32e8977ca95aac160784598d75 which fixes this problem. Courtesy of @denysvitali. I still need to update the docs.

The problem was caused by:
https://github.com/waarzitjenu/map/blob/10cc2f268afdb94f82a7912e815caf345a423a13/src/components/Mapbox.vue#L40
which has been replaced by:
https://github.com/waarzitjenu/map/blob/5bf01903e3e10a32e8977ca95aac160784598d75/src/components/Mapbox.vue#L40

Please let me know when it works or when you need any further assistance with it 👍🏼

**Comment by TheLastGimbus** [comment]
I `git pull`ed and `docker-compose down && docker-compose up --build`ed (actually I burned every volume to the ground and re built it from scratch multiple times), and still same 404:

![image](https://user-images.githubusercontent.com/40139196/120727721-90bb2d80-c4db-11eb-828c-84011788af40.png)

**Comment by denysvitali** [comment]
For some reason your project seems to still have that stylesheet.

Two things:
- can you please confirm (`git rev-parse HEAD`) that you're using the latest commit?
- can you please clear the cache of your browser / try with incognito mode?

**Comment by TheLastGimbus** [comment]
```bash
 git log
commit 0f4fa5dd1b99dfa452e19b5848b6f60c822043df (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 16ac009 aad3935
Author: Ricardo Balk <14904229+ricardobalk@users.noreply.github.com>
Date:   Thu Dec 24 15:59:14 2020 +0100

    Merge branch 'feature/issues/#56-operation-flashback' into develop
```

Incognito / ctr+shift+r / opening in another browser doesn't work

**Comment by denysvitali** [comment]
Oh yes right, @ricardobalk you need to bump the submodule version on develop here.

For you @TheLastGimbus , do:

```
cd web
git pull
```

And try again :)

**Comment by ricardobalk** [comment]
Actually, I'm planning to remove the submodule from the Git repo (#60).

So I have to...
- Do everything as described in #60
- Update the Docker Compose file in this repo

Will do that right away. :+1:

**Comment by ricardobalk** [comment]
Finished it.

- Try to pull the latest version of this repository, waarzitjenu/server
- In a shell environment, pass your environment variables:
   ```sh
   export LOCATION_API_ENDPOINT=http://localhost:8080/retrieve
   export MAPBOX_ACCESS_TOKEN=<your mapbox access token here>
   ```
- Then, build and run the new docker-compose file:
  ```sh
  docker-compose build --no-cache
  docker-compose up
  ```

**Comment by TheLastGimbus** [comment]
I serve my stuff with Caddy - should I now expose map port as `waar.mydomain` and server as `api.waar.mydomain`, or what would you recommend to me?

**Comment by denysvitali** [comment]
@TheLastGimbus That sounds like a good option to me :)
